{{- define "news-services.image-service-deployment" -}}
{{- include "common.deployment" . | nindent 0}}
            - name: BOOTSTRAP_SERVERS
              value: {{ .Values.bootstrapServers }}
            - name: KAFKA_CONSUMER_GROUP
              value: {{ .Values.kafkaConsumerGroup }}
            - name: IMAGES_TO_PROCESS_TOPIC_PARTITIONS
              value: "1"
            - name: IMAGES_TO_PROCESS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: IMAGES_TO_PROCESS_TOPIC_NAME
              value: {{ .Values.kafkaImagesToProcessTopic }}
            - name: PROCESSED_IMAGES_TOPIC_NAME
              value: {{ .Values.kafkaProcessedImagesTopic }}
            - name: PROCESSED_IMAGES_TOPIC_PARTITIONS
              value: "1"
            - name: PROCESSED_IMAGES_REPLICATION_FACTOR
              value: "1"
            - name: S3_BUCKET_PREFIX
              value: {{ .Values.s3BucketPrefix }}
            - name: S3_REGION
              value: {{ .Values.s3Region}}
            - name: S3_BUCKET
              value: {{ .Values.s3Bucket }}
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: image-s3bucket-secret
                  key: accessKey
            - name: S3_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: image-s3bucket-secret
                  key: accessSecret
{{- end -}}
