{{- define "news-services.ingester-deployment" -}}
{{- include "common.deployment" . | nindent 0}}
            - name: BOOTSTRAP_SERVERS
              value: {{ .Values.bootstrapServers }}
            - name: KAFKA_CONSUMER_GROUP
              value: {{ .Values.kafkaConsumerGroup }}
            - name: PROCESSED_IMAGES_TOPIC_NAME
              value: {{ .Values.kafkaProcessedImagesTopic }}
            - name: IMAGES_TO_PROCESS_TOPIC_NAME
              value: { { .Values.kafkaImagesToProcessTopic } }
            - name: DATASOURCE_URL
              value: {{ .Values.datasourceUrl }}
            - name: DATASOURCE_USERNAME
              value: {{ .Values.datasourceUserName }}
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: datasource-secret
                    key: password
            - name: NEWS_API_TOKEN
              valueFrom:
                 secretKeyRef:
                    name: news-api-secret
                    key: token
{{- end -}}
