{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.deploymentNamespace }}
  name: {{ .Values.deploymentLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Values.deploymentLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentLabel }}
    spec:
      containers:
        - name: {{ .Values.deploymentLabel }}
          image: "{{ .Values.repository }}:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: JAVA_OPTS
              value: {{ .Values.java_opts}}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
{{- end -}}
